[versions]

# https://kotlinlang.org/docs/releases.html#release-details
kotlin = "1.9.21"
# https://github.com/Kotlin/kotlinx-atomicfu
kotlinxAtomicfu = "0.23.0"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinxCollectionsImmutable = "0.3.6"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinxCoroutines = "1.7.3"
# https://github.com/square/kotlinpoet
kotlinPoet = "1.14.2"
# https://www.slf4j.org/news.html
slf4j = "1.7.36"
# https://logback.qos.ch/news.html
logback = "1.2.11"
# https://junit.org/junit4/
junit = "4.13.2"

###############  Plugins ###################

# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
gradlePluginPublish = "1.2.0"
# https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
androidPlugin = "7.2.2"
# https://github.com/Kotlin/dokka
dokkaPlugin = "1.9.10"


[libraries]

kotlinGradlePlugin =  { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidGradlePlugin =  { module = "com.android.tools.build:gradle", version.ref = "androidPlugin" }
dokkaPlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaPlugin" }

kotlinxAtomicfu =  { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }
kotlinxCollectionsImmutable =  { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinxCoroutinesCore =  { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest =  { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinPoet =  { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
slf4jApi =  { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logbackClassic =  { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit =  { module = "junit:junit", version.ref = "junit" }


[plugins]

gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
dokkaPlugin = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
