[versions]

# https://kotlinlang.org/docs/releases.html#release-dbbbetails
kotlin = "2.2.0"
# https://github.com/Kotlin/kotlinx-atomicfu
kotlinxAtomicfu = "0.29.0"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinxCollectionsImmutable = "0.4.0"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinxCoroutines = "1.10.2"
# https://github.com/Kotlin/kotlinx.serialization
kotlinxSerialization = "1.9.0"
# https://github.com/square/kotlinpoet
kotlinPoet = "2.2.0"
# https://www.slf4j.org/news.html
slf4j = "2.0.17"
# https://logback.qos.ch/news.html
logback = "1.5.17"
# https://junit.org/junit4/
junit = "4.13.2"
# https://github.com/ZacSweers/kotlin-compile-testing
kotlinCompileTesting = "0.8.0"
#https://developer.android.com/jetpack/androidx/releases/core
androidXcore = "1.16.0"

###############  Plugins ###################

# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
gradlePluginPublish = "1.3.1"
# https://mvnrepository.com/artifact/org.jetbrains.compose/compose-gradle-plugin
composePlugin = "1.8.0"
# https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
androidPlugin = "8.10.1"
# https://github.com/Kotlin/dokka
dokkaPlugin = "1.9.20"


[libraries]

kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
composeGradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composePlugin" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidPlugin" }
dokkaPlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaPlugin" }

kotlinxAtomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }
kotlinxCollectionsImmutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidXcore" }
kotlinCompileTesting = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlinCompileTesting" }

[plugins]

gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
dokkaPlugin = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
